<%@ page language="java" contentType="text/html; charset=utf-8"
	pageEncoding="utf-8"%>
<ul class="easyui-tree" animate="true" lines="true" >
	<li><span>商品管理</span>
	<ul>
			<li class="selected"><a
				href="/iwebshop/index.php?controller=goods&amp;action=goods_list">商品列表</a></li>
			<li><a
				href="/iwebshop/index.php?controller=goods&amp;action=goods_add">商品添加</a></li>
		</ul></li>
	<li><span>商品分类</span>
	<ul>
			<li><a
				href="/iwebshop/index.php?controller=goods&amp;action=category_list">分类列表</a></li>
			<li><a
				href="/iwebshop/index.php?controller=goods&amp;action=category_edit">添加分类</a></li>
		</ul></li>
	<li><span>品牌</span>
	<ul>
			<li><a
				href="/iwebshop/index.php?controller=brand&amp;action=category_list">品牌分类</a></li>
			<li><a
				href="/iwebshop/index.php?controller=brand&amp;action=brand_list">品牌列表</a></li>
		</ul></li>
	<li><span>模型</span>
	<ul>
			<li><a
				href="/iwebshop/index.php?controller=goods&amp;action=model_list">模型列表</a></li>
			<li><a
				href="/iwebshop/index.php?controller=goods&amp;action=spec_list">规格列表</a></li>
			<li><a
				href="/iwebshop/index.php?controller=goods&amp;action=spec_photo">规格图库</a></li>
		</ul></li>
	<li><span>热门搜索</span>
	<ul>
			<li><a
				href="/iwebshop/index.php?controller=tools&amp;action=keyword_list">关键词列表</a></li>
			<li><a
				href="/iwebshop/index.php?controller=tools&amp;action=search_list">搜索统计</a></li>
		</ul></li>
</ul>